import test from 'node:test';
import assert from 'node:assert/strict';
import {createDeliveryService,usernameEmail,customerEmail,securePassword,validateOrder,trackingToken,publicTracking} from '../assets/v1/delivery-core.mjs';
function fixture(){
 const apps=new Map(),auths=new Map(),records=new Map(),writes=[],listeners=[];let failProfile=false,deleted=false;const now={toMillis:()=>123};
 const sdk={initializeApp(config,name){const a={name};apps.set(name,a);return a;},getAuth(app){if(!auths.has(app.name))auths.set(app.name,{currentUser:null});return auths.get(app.name);},getFirestore:()=>({}),setPersistence:async()=>{},browserSessionPersistence:'session',inMemoryPersistence:'memory',signInWithEmailAndPassword:async(a,email)=>{a.currentUser={uid:email==='admin@test.com'?'admin':'clientA',isAnonymous:false,emailVerified:true,email:'cliente@example.com'};return {user:a.currentUser};},signOut:async a=>{a.currentUser=null;},onAuthStateChanged:(a,fn)=>{listeners.push(fn);return ()=>{};},doc:(db,path,id)=>{if(db?.path)return {path:db.path+'/new-order',id:'new-order'};return {path:path+'/'+id,id};},collection:(db,path)=>({path}),query:(ref,filter)=>({...ref,filter}),where:(field,op,value)=>({field,op,value}),getDoc:async ref=>({exists:()=>records.has(ref.path),data:()=>records.get(ref.path)}),serverTimestamp:()=>now,setDoc:async(ref,data)=>{if(failProfile&&ref.path.startsWith('deliveryCustomers/'))throw Error('Profile failure');records.set(ref.path,data);writes.push({ref,data});},onSnapshot:(ref,fn,fail)=>{listeners.push({ref,fn,fail});return ()=>{};},createUserWithEmailAndPassword:async(a,email,password)=>{const user={uid:'new-customer',isAnonymous:false,emailVerified:true,email:'cliente@example.com'};a.currentUser=user;return {user};},deleteUser:async()=>{deleted=true;},deleteApp:async a=>apps.delete(a.name),sendEmailVerification:async()=>{},sendPasswordResetEmail:async()=>{},reload:async()=>{},getIdToken:async()=>{},updatePassword:async()=>{},runTransaction:async(db,fn)=>fn({get:sdk.getDoc,set:(ref,data)=>{records.set(ref.path,data);writes.push({ref,data});},update:(ref,data)=>{records.set(ref.path,{...records.get(ref.path),...data});writes.push({ref,data});}})};
 records.set('deliveryAdmins/admin',{enabled:true});records.set('deliveryCustomers/clientA',{name:'Cliente A'});
 return {sdk,records,writes,listeners,auths,apps,setFailProfile:()=>failProfile=true,wasDeleted:()=>deleted};
}
const input={customerUid:'clientA',details:'2 tazas sublimadas',address:'Dirección del cliente',amount:'30',deliveryFee:'5',estimatedAt:'2026-10-05T18:00:00-05:00',status:'recibido'};
test('assigned usernames are validated, normalized, and passwords are random',()=>{assert.equal(usernameEmail(' Cliente.Maria@Correo.com '),'cliente.maria@correo.com');assert.throws(()=>usernameEmail('sin-correo'));assert.throws(()=>usernameEmail('../admin'));const one=securePassword(),two=securePassword();assert.equal(one.length,36);assert.notEqual(one,two);});
test('invalid amounts/status/date are rejected; zero costs allowed',()=>{assert.equal(validateOrder(input).amount,30);assert.equal(validateOrder({...input,amount:0,deliveryFee:0}).deliveryFee,0);for(const bad of [{amount:''},{amount:-1},{deliveryFee:'abc'},{amount:Infinity},{status:'inventado'},{estimatedAt:'invalid'},{details:''}])assert.throws(()=>validateOrder({...input,...bad}));});
test('client query is scoped to own UID and cannot perform admin actions',async()=>{const f=fixture(),s=createDeliveryService(f.sdk,{});await s.login('cliente.a','password');s.subscribeOrders(()=>{},()=>{});assert.deepEqual(f.listeners[0].ref.filter,{field:'customerUid',op:'==',value:'clientA'});await assert.rejects(s.createOrder(input),/autorizada/);assert.throws(()=>s.subscribeOrders(()=>{},()=>{},true));await assert.rejects(s.createCustomer({name:'X',username:'xxx@example.com'}));assert.equal(f.writes.length,0);});
test('non-admin login to store panel is rejected and clears auth',async()=>{const f=fixture(),s=createDeliveryService(f.sdk,{});await assert.rejects(s.login('client@test.com','password',true),/autorizada/);assert.equal(f.auths.get('grafiplot-delivery').currentUser,null);});
test('provisioning keeps admin session and never saves password to Firestore',async()=>{const f=fixture(),s=createDeliveryService(f.sdk,{});await s.login('admin@test.com','password',true);const account=await s.createCustomer({name:'Maria',username:'maria',password:'clave123',phone:'123'});assert.equal(account.username,'maria');assert.equal(f.auths.get('grafiplot-delivery').currentUser.uid,'admin');assert.equal(f.apps.size,1);assert.equal(f.records.get('deliveryCustomers/new-customer').password,undefined);assert.equal(account.password,'clave123');});
test('failed profile write cleans up only newly provisioned account',async()=>{const f=fixture(),s=createDeliveryService(f.sdk,{});await s.login('admin@test.com','password',true);f.setFailProfile();await assert.rejects(s.createCustomer({name:'Maria',username:'maria',password:'clave123'}),/Profile failure/);assert.equal(f.wasDeleted(),true);assert.equal(f.auths.get('grafiplot-delivery').currentUser.uid,'admin');});
test('order updates keep owner; departure and delivery timestamps follow states',async()=>{const f=fixture(),s=createDeliveryService(f.sdk,{});await s.login('admin@test.com','password',true);const id=await s.createOrder(input);assert.equal(id,'new-order');const path='deliveryOrders/new-order';assert.equal(f.records.get(path).leftStoreAt,null);await s.updateOrder(id,{...input,customerUid:'other',status:'en_camino'});assert.equal(f.records.get(path).customerUid,'clientA');assert.ok(f.records.get(path).leftStoreAt);assert.equal(f.records.get(path).deliveredAt,null);await s.updateOrder(id,{...input,status:'entregado'});assert.ok(f.records.get(path).deliveredAt);await s.updateOrder(id,{...input,status:'en_proceso'});assert.equal(f.records.get(path).leftStoreAt,null);assert.equal(f.records.get(path).deliveredAt,null);});
test('logout revokes admin actions locally',async()=>{const f=fixture(),s=createDeliveryService(f.sdk,{});await s.login('admin@test.com','password',true);await s.logout();await assert.rejects(s.createOrder(input));assert.throws(()=>s.subscribeOrders(()=>{},()=>{}));});

test('unverified account cannot read or manage deliveries',async()=>{const f=fixture(),s=createDeliveryService(f.sdk,{});await s.login('admin@test.com','password',true);f.auths.get('grafiplot-delivery').currentUser.emailVerified=false;assert.throws(()=>s.subscribeOrders(()=>{},()=>{},true));await assert.rejects(s.createOrder(input));});
test('password recovery hides whether email exists',async()=>{const f=fixture();f.sdk.sendPasswordResetEmail=async()=>{throw Object.assign(Error('Not found'),{code:'auth/user-not-found'});};const s=createDeliveryService(f.sdk,{});await s.resetPassword('none@example.com');await assert.rejects(s.resetPassword('invalid'));});

test("assigned customer does not need email verification",async()=>{assert.equal(customerEmail(" Maria123 "),"maria123@delivery.grafiplotvasquez.com");assert.throws(()=>customerEmail("maria@correo.com"));const f=fixture(),s=createDeliveryService(f.sdk,{});await s.login("maria123","clave123");f.auths.get("grafiplot-delivery").currentUser.emailVerified=false;s.subscribeOrders(()=>{},()=>{});assert.equal(f.listeners[0].ref.filter.value,"clientA");});

test('private tracking omits personal data and expires on delivered orders',async()=>{const token=trackingToken();assert.match(token,/^[a-f0-9]{64}$/);assert.notEqual(token,trackingToken());const f=fixture(),s=createDeliveryService(f.sdk,{});await s.login('admin@test.com','password',true);const id=await s.createOrder(input);const order=f.records.get('deliveryOrders/'+id);const linkPath='deliveryOrderLinks/'+order.trackingToken;assert.equal(f.records.get(linkPath).address,undefined);assert.equal(f.records.get(linkPath).customerUid,undefined);assert.equal(f.records.get(linkPath).customerName,undefined);await s.updateOrder(id,{...input,status:'entregado'});assert.equal(f.records.get(linkPath).expiresAt.getTime(),0);await assert.rejects(s.createTrackingLink(id),/concluyó/);});
test('replacing tracking link revokes the old one; customers cannot create links',async()=>{const f=fixture(),s=createDeliveryService(f.sdk,{});await s.login('admin@test.com','password',true);const id=await s.createOrder(input);const old=f.records.get('deliveryOrders/'+id).trackingToken;const next=await s.createTrackingLink(id);assert.notEqual(old,next);assert.equal(f.records.get('deliveryOrderLinks/'+old).expiresAt.getTime(),0);assert.equal(f.records.get('deliveryOrders/'+id).trackingToken,next);await s.logout();await assert.rejects(s.createTrackingLink(id));assert.throws(()=>s.subscribeTracking('bad',()=>{},()=>{}));});

test('sharing repairs missing or expired projections and reads the customer only as admin',async()=>{const f=fixture(),s=createDeliveryService(f.sdk,{});await assert.rejects(s.getCustomer('clientA'));await s.login('admin@test.com','password',true);assert.equal((await s.getCustomer('clientA')).name,'Cliente A');const id=await s.createOrder(input),orderPath='deliveryOrders/'+id;const first=f.records.get(orderPath).trackingToken;assert.equal(await s.ensureTrackingLink(id),first);f.records.delete('deliveryOrderLinks/'+first);const second=await s.ensureTrackingLink(id);assert.notEqual(second,first);f.records.get('deliveryOrderLinks/'+second).expiresAt=new Date(0);const third=await s.ensureTrackingLink(id);assert.notEqual(third,second);await s.updateOrder(id,{...input,status:'entregado'});await assert.rejects(s.ensureTrackingLink(id),/concluyó/);});
