import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {parseHTML} from 'linkedom';
import {STATES} from '../assets/v1/delivery-core.mjs';
const html=await readFile(new URL('../delivery.html',import.meta.url),'utf8');
const source=(await readFile(new URL('../assets/v1/delivery.js',import.meta.url),'utf8')).replace(/^import .*;$/gm,'').replace(/await import\('\.\/delivery-sdk\.js\?v=[^']+'\)/g,'({})');
const adminHtml=await readFile(new URL('../delivery-admin.html',import.meta.url),'utf8');
function mount(enabled,service={},admin=false,clipboard=async()=>{}){const {window,document}=parseHTML(admin==='tracking'?html.replace('data-delivery-role="customer"','data-delivery-role="tracking"'):admin?adminHtml:html);window.HTMLElement.prototype.scrollIntoView=function(){};for(const select of document.querySelectorAll('select'))select.add=n=>select.append(n);for(const form of document.querySelectorAll('form'))form.reset=()=>{};const context={document,window,console,Intl,Date,URL,location:{hash:'#'+'a'.repeat(64),href:'https://example.com/delivery-admin.html'},navigator:{clipboard:{writeText:clipboard}},Option:function(text,value){const n=document.createElement('option');n.textContent=text;n.value=value;return n;},STATES,DELIVERY_ENABLED:enabled,USER_FIREBASE_CONFIG:{},createDeliveryService:()=>service};vm.runInNewContext(source,context);return {window,document};}
const tick=()=>new Promise(r=>setImmediate(r));
test('unconfigured delivery never initializes Firebase and disables login',async()=>{const {document}=mount(false);await tick();assert.equal(document.querySelector('#setup-notice').hidden,false);assert.equal(document.querySelector('#login-form button').disabled,true);assert.equal(document.querySelector('#username').disabled,true);assert.equal(document.querySelector('#customer-panel').hidden,true);});
test('customer receives live status, fees, eta and details without HTML execution; logout clears orders',async()=>{let session,receive;const service={watchSession:async fn=>{session=fn;},subscribeOrders:fn=>{receive=fn;return ()=>{};},logout:async()=>session(null,false)};const {document,window}=mount(true,service);await tick();assert.equal(document.querySelector('#login-form button').disabled,false);session({uid:'a',emailVerified:true,email:'a@example.com'},false);receive([{id:'abc12345',customerUid:'a',status:'en_camino',details:'<img src=x onerror=alert(1)> 2 tazas',address:'Mi dirección',amount:30,deliveryFee:5,estimatedAt:new Date('2026-10-05T23:00:00Z'),leftStoreAt:new Date('2026-10-05T22:30:00Z'),updatedAt:new Date('2026-10-05T22:30:00Z')}]);assert.equal(document.querySelector('#customer-panel').hidden,false);assert.match(document.querySelector('#orders').textContent,/Salió con el delivery/);assert.match(document.querySelector('#orders').textContent,/35/);assert.match(document.querySelector('#orders').textContent,/Mi dirección/);assert.equal(document.querySelector('#orders img'),null);assert.equal(document.querySelector('[aria-current=step]').textContent,'Salió con el delivery');document.querySelector('#logout').dispatchEvent(new window.Event('click'));await tick();assert.equal(document.querySelector('#orders').textContent,'');assert.equal(document.querySelector('#customer-panel').hidden,true);});
test('delivery subscriber failure hides stale private data and explains access error',async()=>{let session,fail;const {document}=mount(true,{watchSession:async fn=>session=fn,subscribeOrders:(fn,error)=>{fail=error;return ()=>{};}});await tick();session({uid:'a',emailVerified:true,email:'a@example.com'},false);fail({code:'permission-denied'});assert.equal(document.querySelector('#customer-panel').hidden,true);assert.match(document.querySelector('#feedback').textContent,/permiso/);});

test('customer enters without email verification and receives own orders',async()=>{let session,calls=0;const {document}=mount(true,{watchSession:async fn=>session=fn,subscribeOrders:()=>{calls++;}});await tick();session({uid:'a',emailVerified:false,email:'a@example.com'},false);assert.equal(document.querySelector('#verify-panel').hidden,true);assert.equal(document.querySelector('#customer-panel').hidden,false);assert.equal(calls,1);});

test('recovery opens a dedicated form, sends the supplied email and displays Firebase errors',async()=>{let requested;const service={watchSession:async()=>{},resetPassword:async email=>{requested=email;}};const {document,window}=mount(true,service,true);await tick();document.querySelector('#reset-password').dispatchEvent(new window.Event('click'));assert.equal(document.querySelector('#recovery-panel').hidden,false);assert.equal(document.querySelector('#recovery-submit').disabled,false);document.querySelector('#recovery-email').value='admin@example.com';document.querySelector('#recovery-form').dispatchEvent(new window.Event('submit'));await tick();assert.equal(requested,'admin@example.com');assert.match(document.querySelector('#recovery-feedback').textContent,/Solicitud aceptada/);service.resetPassword=async()=>{throw {code:'auth/network-request-failed'};};document.querySelector('#recovery-form').dispatchEvent(new window.Event('submit'));await tick();assert.match(document.querySelector('#recovery-feedback').textContent,/conexión/);assert.equal(document.querySelector('#recovery-submit').disabled,false);});

test('private tracking uses the token without a login and clears data on revocation',async()=>{let receive,fail,authCalls=0;const {document}=mount(true,{watchSession:async()=>authCalls++,subscribeTracking:(token,next,error)=>{assert.equal(token,'a'.repeat(64));receive=next;fail=error;return ()=>{};}},'tracking');await tick();assert.equal(authCalls,0);assert.equal(document.querySelector('#login-panel').hidden,true);receive([{id:'pedido',status:'recibido',details:'Dos tazas',amount:25,deliveryFee:5}]);assert.equal(document.querySelector('#customer-panel').hidden,false);fail();assert.equal(document.querySelector('#orders').textContent,'');assert.equal(document.querySelector('#customer-panel').hidden,true);assert.match(document.querySelector('#feedback').textContent,/dejó de estar disponible/);});
test('delivered orders leave active list and remain available only in history',async()=>{let session,receive;const service={watchSession:async fn=>session=fn,subscribeOrders:fn=>{receive=fn;return ()=>{};},subscribeCustomers:()=>()=>{}};const {document,window}=mount(true,service,true);await tick();session({uid:'admin',emailVerified:true},true);receive([{id:'active',customerName:'Ana',details:'Activo',status:'recibido',amount:10,deliveryFee:0},{id:'complete',customerName:'Luis',details:'Concluido',status:'entregado',amount:15,deliveryFee:0}]);assert.match(document.querySelector('#admin-orders').textContent,/Ana/);assert.doesNotMatch(document.querySelector('#admin-orders').textContent,/Luis/);document.querySelector('#order-view option[value=history]').setAttribute('selected','');document.querySelector('#order-view').dispatchEvent(new window.Event('change'));assert.match(document.querySelector('#admin-orders').textContent,/Luis/);assert.doesNotMatch(document.querySelector('#admin-orders').textContent,/Copiar enlace|Generar enlace/);});

test('WhatsApp message includes client username, supplied password and private link; closing clears secrets',async()=>{
 let session,receive,receiveCustomers,copied='';const service={watchSession:async fn=>session=fn,subscribeOrders:fn=>{receive=fn;return ()=>{};},subscribeCustomers:fn=>{receiveCustomers=fn;return ()=>{};}};
 const {document,window}=mount(true,service,true,text=>{copied=text;});await tick();session({uid:'admin',emailVerified:true},true);
 receiveCustomers([{uid:'client',name:'Ana',username:'ana123'}]);receive([{id:'pedido',customerUid:'client',customerName:'Ana',details:'Tazas',status:'recibido',amount:20,deliveryFee:5,trackingToken:'a'.repeat(64)}]);
 const button=Array.from(document.querySelectorAll('#admin-orders button')).find(b=>b.textContent==='Copiar mensaje para WhatsApp');button.click();await tick();assert.equal(document.querySelector('#whatsapp-panel').hidden,false);assert.equal(copied,'');
 document.querySelector('#whatsapp-password').value='clave123';document.querySelector('#whatsapp-password').dispatchEvent(new window.Event('input'));document.querySelector('#whatsapp-form').dispatchEvent(new window.Event('submit'));await tick();
 assert.match(copied,/Hola, Ana/);assert.match(copied,/Usuario: ana123/);assert.match(copied,/Contraseña: clave123/);assert.ok(copied.includes('https://example.com/delivery-track.html#'+'a'.repeat(64)));assert.match(copied,/sin ingresar usuario ni contraseña/);
 document.querySelector('#whatsapp-close').click();assert.equal(document.querySelector('#whatsapp-password').value,'');assert.equal(document.querySelector('#whatsapp-message').value,'');assert.equal(document.querySelector('#whatsapp-panel').hidden,true);
});
test('new client password prefills WhatsApp only in memory and logout clears the message',async()=>{
 let session,receive,receiveCustomers,copied='';const service={watchSession:async fn=>session=fn,subscribeOrders:fn=>{receive=fn;return ()=>{};},subscribeCustomers:fn=>{receiveCustomers=fn;return ()=>{};},createCustomer:async()=>({uid:'client',username:'ana123',password:'clave456'}),createTrackingLink:async()=> 'b'.repeat(64),logout:async()=>session(null,false)};
 const {document,window}=mount(true,service,true,text=>{copied=text;});await tick();session({uid:'admin',emailVerified:true},true);document.querySelector('#customer-form').reset=()=>{};document.querySelector('#customer-form').dispatchEvent(new window.Event('submit'));await tick();receiveCustomers([{uid:'client',name:'Ana',username:'ana123'}]);receive([{id:'pedido',customerUid:'client',customerName:'Ana',details:'Tazas',status:'recibido',amount:20,deliveryFee:5}]);
 Array.from(document.querySelectorAll('#admin-orders button')).find(b=>b.textContent==='Copiar mensaje para WhatsApp').click();await tick();assert.match(copied,/Contraseña: clave456/);assert.ok(copied.includes('#'+'b'.repeat(64)));
 document.querySelector('#logout').click();await tick();assert.equal(document.querySelector('#whatsapp-password').value,'');assert.equal(document.querySelector('#whatsapp-message').value,'');assert.equal(document.querySelector('#whatsapp-panel').hidden,true);
});
