import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';
import {readFile} from 'node:fs/promises';
import {test,before,after} from 'node:test';
import {doc,setDoc,getDoc,updateDoc,collection,getDocs,query,where,serverTimestamp,Timestamp} from 'firebase/firestore';
let env;
const claims={email_verified:true,firebase:{sign_in_provider:'password'}};
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-grafiplot-delivery',firestore:{rules:await readFile(new URL('../firebase/firestore.production.rules',import.meta.url),'utf8')}});await env.withSecurityRulesDisabled(async context=>{const db=context.firestore();await setDoc(doc(db,'deliveryAdmins/admin'),{enabled:true});for(const uid of ['a','b'])await setDoc(doc(db,'deliveryCustomers/'+uid),{name:'Cliente '+uid,email:uid+'@example.com',phone:'',createdAt:Timestamp.now()});for(const uid of ['a','b'])await setDoc(doc(db,'deliveryOrders/order-'+uid),{customerUid:uid,customerName:'Cliente '+uid,details:'Trabajo',address:'Dirección',amount:20,deliveryFee:5,status:'recibido',estimatedAt:null,createdAt:Timestamp.now(),updatedAt:Timestamp.now(),leftStoreAt:null,deliveredAt:null});});});
after(async()=>{await env?.cleanup();});
const db=uid=>env.authenticatedContext(uid,claims).firestore();
test('customer can only read own orders, not unfiltered collection',async()=>{const a=db('a');await assertSucceeds(getDoc(doc(a,'deliveryOrders/order-a')));await assertFails(getDoc(doc(a,'deliveryOrders/order-b')));await assertSucceeds(getDocs(query(collection(a,'deliveryOrders'),where('customerUid','==','a'))));await assertFails(getDocs(collection(a,'deliveryOrders')));});
test('anonymous and signed-out visitors cannot read deliveries',async()=>{for(const d of [env.unauthenticatedContext().firestore(),env.authenticatedContext('a',{firebase:{sign_in_provider:'anonymous'}}).firestore()])await assertFails(getDoc(doc(d,'deliveryOrders/order-a')));});
test('customer cannot change costs/status/owner or create own order',async()=>{const a=db('a');for(const patch of [{amount:0},{status:'entregado'},{customerUid:'b'}])await assertFails(updateDoc(doc(a,'deliveryOrders/order-a'),patch));await assertFails(setDoc(doc(a,'deliveryOrders/fake'),{customerUid:'a'}));});
test('role self-assignment and customer listing are blocked',async()=>{const a=db('a');await assertFails(setDoc(doc(a,'deliveryAdmins/a'),{enabled:true}));await assertFails(getDoc(doc(a,'deliveryAdmins/admin')));await assertFails(getDocs(collection(a,'deliveryCustomers')));await assertFails(getDoc(doc(a,'deliveryCustomers/b')));await assertSucceeds(getDoc(doc(a,'deliveryCustomers/a')));});
test('admin may list and update valid orders but not transfer ownership or inject passwords',async()=>{const admin=db('admin');await assertSucceeds(getDocs(collection(admin,'deliveryOrders')));await assertSucceeds(updateDoc(doc(admin,'deliveryOrders/order-a'),{status:'en_camino',leftStoreAt:serverTimestamp(),updatedAt:serverTimestamp()}));await assertSucceeds(updateDoc(doc(admin,'deliveryOrders/order-a'),{status:'entregado',deliveredAt:serverTimestamp(),updatedAt:serverTimestamp()}));await assertFails(updateDoc(doc(admin,'deliveryOrders/order-a'),{customerUid:'b',updatedAt:serverTimestamp()}));await assertFails(updateDoc(doc(admin,'deliveryOrders/order-a'),{password:'secret',updatedAt:serverTimestamp()}));await assertFails(updateDoc(doc(admin,'deliveryOrders/order-a'),{amount:-1,updatedAt:serverTimestamp()}));});
test('admin may create customer profile without password',async()=>{const admin=db('admin');await assertSucceeds(setDoc(doc(admin,'deliveryCustomers/new'),{name:'Nuevo',email:'nuevo@example.com',phone:'',createdAt:serverTimestamp()}));await assertFails(setDoc(doc(admin,'deliveryCustomers/bad'),{name:'Nuevo',email:'bad@example.com',phone:'',createdAt:serverTimestamp(),password:'secret'}));});

test('legacy authenticated site access preserved outside delivery, no signed-out writes',async()=>{const anonymous=env.authenticatedContext('site-anon',{firebase:{sign_in_provider:'anonymous'}}).firestore();await assertSucceeds(setDoc(doc(anonymous,'artifacts/grafiplot-tienda-v4/public/data/settings/config'),{testOnly:true}));await assertSucceeds(getDoc(doc(anonymous,'artifacts/grafiplot-tienda-v4/public/data/settings/config')));await assertFails(setDoc(doc(env.unauthenticatedContext().firestore(),'artifacts/grafiplot-tienda-v4/public/data/settings/config'),{testOnly:true}));});

test('unverified clients and admins cannot read private orders',async()=>{for(const uid of ['a','admin']){const unverified=env.authenticatedContext(uid,{email_verified:false,firebase:{sign_in_provider:'password'}}).firestore();await assertFails(getDoc(doc(unverified,'deliveryOrders/order-a')));}const unverifiedAdmin=env.authenticatedContext('admin',{email_verified:false,firebase:{sign_in_provider:'password'}}).firestore();await assertSucceeds(getDoc(doc(unverifiedAdmin,'deliveryAdmins/admin')));});
