import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {parseHTML} from 'linkedom';
import {STATES} from '../assets/v1/delivery-core.mjs';
const html=await readFile(new URL('../delivery.html',import.meta.url),'utf8');
const source=(await readFile(new URL('../assets/v1/delivery.js',import.meta.url),'utf8')).replace(/^import .*;$/gm,'').replace("await import('./delivery-sdk.js')",'({})');
function mount(enabled,service={}){const {window,document}=parseHTML(html);window.HTMLElement.prototype.scrollIntoView=function(){};const context={document,window,console,Intl,Date,Option:function(text,value){const n=document.createElement('option');n.textContent=text;n.value=value;return n;},STATES,DELIVERY_ENABLED:enabled,USER_FIREBASE_CONFIG:{},createDeliveryService:()=>service};vm.runInNewContext(source,context);return {window,document};}
const tick=()=>new Promise(r=>setImmediate(r));
test('unconfigured delivery never initializes Firebase and disables login',async()=>{const {document}=mount(false);await tick();assert.equal(document.querySelector('#setup-notice').hidden,false);assert.equal(document.querySelector('#login-form button').disabled,true);assert.equal(document.querySelector('#username').disabled,true);assert.equal(document.querySelector('#customer-panel').hidden,true);});
test('customer receives live status, fees, eta and details without HTML execution; logout clears orders',async()=>{let session,receive;const service={watchSession:async fn=>{session=fn;},subscribeOrders:fn=>{receive=fn;return ()=>{};},logout:async()=>session(null,false)};const {document,window}=mount(true,service);await tick();assert.equal(document.querySelector('#login-form button').disabled,false);session({uid:'a'},false);receive([{id:'abc12345',customerUid:'a',status:'en_camino',details:'<img src=x onerror=alert(1)> 2 tazas',address:'Mi dirección',amount:30,deliveryFee:5,estimatedAt:new Date('2026-10-05T23:00:00Z'),leftStoreAt:new Date('2026-10-05T22:30:00Z'),updatedAt:new Date('2026-10-05T22:30:00Z')}]);assert.equal(document.querySelector('#customer-panel').hidden,false);assert.match(document.querySelector('#orders').textContent,/Salió con el delivery/);assert.match(document.querySelector('#orders').textContent,/35/);assert.match(document.querySelector('#orders').textContent,/Mi dirección/);assert.equal(document.querySelector('#orders img'),null);assert.equal(document.querySelector('[aria-current=step]').textContent,'Salió con el delivery');document.querySelector('#logout').dispatchEvent(new window.Event('click'));await tick();assert.equal(document.querySelector('#orders').textContent,'');assert.equal(document.querySelector('#customer-panel').hidden,true);});
test('delivery subscriber failure hides stale private data and explains access error',async()=>{let session,fail;const {document}=mount(true,{watchSession:async fn=>session=fn,subscribeOrders:(fn,error)=>{fail=error;return ()=>{};}});await tick();session({uid:'a'},false);fail({code:'permission-denied'});assert.equal(document.querySelector('#customer-panel').hidden,true);assert.match(document.querySelector('#feedback').textContent,/permiso/);});
