import {initializeTestEnvironment,assertFails,assertSucceeds} from '@firebase/rules-unit-testing';import {readFile} from 'node:fs/promises';import {test,before,after} from 'node:test';import {doc,setDoc,getDoc,getDocs,collection,writeBatch,Timestamp,serverTimestamp} from 'firebase/firestore';let env;
const token='a'.repeat(64),nextToken='b'.repeat(64);const orderPath='deliveryOrders/tracking-test';const linkPath='deliveryOrderLinks/'+token;
const baseOrder={customerUid:'client',customerName:'Cliente',details:'Dos tazas',address:'Privada',amount:25,deliveryFee:5,status:'recibido',estimatedAt:null,createdAt:Timestamp.now(),updatedAt:Timestamp.now(),leftStoreAt:null,deliveredAt:null,trackingToken:token};const projection=o=>({orderId:'tracking-test',details:o.details,amount:o.amount,deliveryFee:o.deliveryFee,status:o.status,estimatedAt:o.estimatedAt,updatedAt:o.updatedAt,leftStoreAt:o.leftStoreAt,deliveredAt:o.deliveredAt,expiresAt:Timestamp.fromMillis(Date.now()+86400000)});
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-grafiplot-delivery',firestore:{rules:await readFile(new URL('../firebase/firestore.production.rules',import.meta.url),'utf8')}});await env.withSecurityRulesDisabled(async ctx=>{const db=ctx.firestore();await setDoc(doc(db,'deliveryAdmins/tracking-admin'),{enabled:true});await setDoc(doc(db,'deliveryCustomers/client'),{name:'Cliente'});await setDoc(doc(db,orderPath),baseOrder);await setDoc(doc(db,linkPath),projection(baseOrder));});});after(async()=>env?.cleanup());
test('bearer can read only the exact unexpired link, never list links or read the private order',async()=>{const db=env.unauthenticatedContext().firestore();const data=(await assertSucceeds(getDoc(doc(db,linkPath)))).data();for(const key of ['address','phone','email','customerUid','customerName'])if(key in data)throw Error('Leaked private field '+key);await assertFails(getDocs(collection(db,'deliveryOrderLinks')));await assertFails(getDoc(doc(db,orderPath)));await assertFails(setDoc(doc(db,linkPath),{...data,status:'entregado'}));await assertFails(getDoc(doc(db,'deliveryOrderLinks/not-a-token')));});
test('non-admin cannot publish bearer links',async()=>{const db=env.authenticatedContext('client',{email_verified:true,firebase:{sign_in_provider:'password'}}).firestore();await assertFails(setDoc(doc(db,'deliveryOrderLinks/'+nextToken),projection(baseOrder)));});
test('delivered order immediately revokes bearer access, even if the public projection is stale',async()=>{await env.withSecurityRulesDisabled(async ctx=>setDoc(doc(ctx.firestore(),orderPath),{...baseOrder,status:'entregado'}));await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(),linkPath)));await env.withSecurityRulesDisabled(async ctx=>setDoc(doc(ctx.firestore(),orderPath),baseOrder));});
test('expired and replaced links are denied',async()=>{await env.withSecurityRulesDisabled(async ctx=>setDoc(doc(ctx.firestore(),linkPath),{...projection(baseOrder),expiresAt:Timestamp.fromMillis(0)}));await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(),linkPath)));await env.withSecurityRulesDisabled(async ctx=>{await setDoc(doc(ctx.firestore(),linkPath),projection(baseOrder));await setDoc(doc(ctx.firestore(),orderPath),{...baseOrder,trackingToken:nextToken});});await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(),linkPath)));});

test('admin cannot inject private fields or publish mismatched details',async()=>{const db=env.authenticatedContext('tracking-admin',{email_verified:true,firebase:{sign_in_provider:'password'}}).firestore();const data=projection(baseOrder);await assertFails(setDoc(doc(db,'deliveryOrderLinks/'+nextToken),{...data,address:'Privada'}));await assertFails(setDoc(doc(db,'deliveryOrderLinks/'+nextToken),{...data,amount:999}));await assertSucceeds(setDoc(doc(db,'deliveryOrderLinks/'+nextToken),data));});

test('atomic creation and delivered update synchronize private order and projection',async()=>{const db=env.authenticatedContext('tracking-admin',{email_verified:true,firebase:{sign_in_provider:'password'}}).firestore();const tok='c'.repeat(64),orderId='atomic-tracking';const order={...baseOrder,trackingToken:tok,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};const pub={...projection(order),orderId};let batch=writeBatch(db);batch.set(doc(db,'deliveryOrders/'+orderId),order);batch.set(doc(db,'deliveryOrderLinks/'+tok),pub);await assertSucceeds(batch.commit());await assertSucceeds(getDoc(doc(env.unauthenticatedContext().firestore(),'deliveryOrderLinks/'+tok)));batch=writeBatch(db);batch.update(doc(db,'deliveryOrders/'+orderId),{status:'entregado',leftStoreAt:serverTimestamp(),deliveredAt:serverTimestamp(),updatedAt:serverTimestamp()});batch.update(doc(db,'deliveryOrderLinks/'+tok),{status:'entregado',leftStoreAt:serverTimestamp(),deliveredAt:serverTimestamp(),updatedAt:serverTimestamp(),expiresAt:Timestamp.fromMillis(0)});await assertSucceeds(batch.commit());await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(),'deliveryOrderLinks/'+tok)));});
